### PR TITLE
Ec http pr review

### PR DESCRIPTION
**Pull request by yanndegat**
Add provider test check for iplb
Follow conventions on iplb http resources
Fix iplb http route acc tests

### CODE REVIEW

**Comment by yanndegat** [comment]
hi @eliecharra 

i've checked out your pr and fixed acc tests 
along with rewriting the tests in a more terraform way of doing tests 

let me know if this suits you

**Comment by eliecharra** [comment]
Awsome ! Thanks a lot, I'll check that as soon I have some time :+1:

**Comment by yanndegat** [comment]
hi @eliecharra 

i'm pretty confident in the PR as i've tested it against real iplb by running the acc tests
and by spawning infra with it

i'd like to schedule a provider release in the next days with hashicorp and it would be awesome if 
we could add your new resource within the release

that said, would you mind if 
- i close this PR
- merge your PR on the upstream repo
- push my PR fixing your acc tests on the upstream repo & merge it?

?

**Comment by eliecharra** [comment]
@yanndegat Merged

**Pull request merged**
